#!/bin/sh -
# scwm-snarf 
# (C) 1999 Ken Pizzini and Greg J. Badros
# 	contents of guile-1.4's guile-snarf merged in by Steve Tell
#
## Handle snarfs with embedded %/%/ separating the arglist of procedures
# from the rest.
# See scwm-snarf.h for what expands SCWM_PROC macros to what we process here.
# We need to do a couple of regexp search and replaces:
# s/SCM //g
# s/,[ \t]*//g
# s/"(/"'(/g  # add the Scheme quote to the list -- tricky shell quoting below
# AND we need these to only happen *after* the %/%/ marker on the input lines
# so we use two sed's to do it.

#!/bin/sh
# Extract the initialization actions for builtin things.

temp="/tmp/snarf.$$"
trap "rm -f $temp" 0 1 2 15

## Let the user override the preprocessor autoconf found.
test -n "${CPP+set}" || CPP="gcc -E"

## We must use a temporary file here, instead of a pipe, because we
## need to know if CPP exits with a non-zero status.
${CPP} -DSCM_MAGIC_SNARFER "$@" > ${temp} || exit $?
< ${temp} grep "^ *SCM__I" | sed -e "s/^ *SCM__I//" -e 's/SCM__D.*$//g' | \
sed 's@%/%/@\
@
       /\n/!b
       h
       s/SCM //g
       s/,[ 	]*/ /g
       s/"(/"'\''(/
       x
       G
       s/\n.*\n//' 

## Apparently, AIX's preprocessor is unhappy if you try to #include an
## empty file.
echo

